### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by singhkaran202**
Finally, I updated the  Readme.md file.
I updated the following things:-
1. Added live project link and Screenshot of live project
2. Added badges of "CSS" and "HTML"
3. Added shields for forks, stars, Issues and license
4. Added the link of Code of Conduct 
Below is the screenshots attached of the updated Readme file:-
 
Screenshot(after updation)-1

Screenshot(after updation)-2

### CODE REVIEW

**Review by Sanket1308 — CHANGES_REQUESTED** [review]
Screenshot (1106)
Remove highlighted text

**Comment by singhkaran202** [comment]
@Sanket1308, Could you please view it once again, as requested change is done already(I deleted this text already in my pull request), also the highlighted text is showing red(it infers that this text is deleted).
The related screenshot is attached below:-

Screenshot (2312)_LI

**Comment by Sanket1308** [comment]
Good! Send PR, I'll review it!

**Comment by singhkaran202** [comment]
Yeah sure!!

**Pull request closed without merging**
