### PR TITLE
Updated contributing.md

### PR DESCRIPTION
**Pull request by Shamik1836**

### CODE REVIEW

**Comment by Shamik1836** [comment]
I have updated the contributing.md file. Kindly have a look @Sanket1308

**Comment by Shamik1836** [comment]
Have you checked the updated contributing.md file @Sanket1308

**Comment by Sanket1308** [comment]
This branch has conflicts that must be resolved

**Comment by Shamik1836** [comment]
Okay I am trying to push the commits from a different branch, actually here I have pushed the commits for script.js file too

**Comment by Sanket1308** [comment]
Kindly fetch upstream and make changes and PR again!

**Comment by Shamik1836** [comment]
I am not authorised to make a PR anymore, please allow me at first @Sanket1308

**Pull request closed without merging**
